baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Ταβέρνα Ο Μανώλης'

theme = "blowfish"


# Add any links to things in /content/ here
[[menu.main]]
name = "About"
url = "/about/"
weight = 1
